dataset:
  path: "data"

diffusion:
  num_timesteps: 1000
  noise_schedule: "linear"
  beta_start: 0.0001
  beta_end: 0.02

model:
  img_channels: 1
  img_size: 28
  num_classes: 10
  down_channels: [64, 64, 128, 256]
  mid_channels: [256, 256, 128]
  down_sample: [True, True, False]
  time_embedding_dim: 128
  num_heads: 4

train:
  batch_size: 64
  num_workers: 4
  num_epochs: 100
  lr: 0.0002
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.0
  warmup_steps: 1000
  log_interval: 100
  save_interval: 1000
  resume: False
  resume_path: "checkpoints"
  resume_epoch: 0